name: SpaceX
main: me.reddev.spacex.SpaceX
version: 0.1
author: Zachary Mayhew, Anakin Trotter
commands:
   spacex:
      description: the main spacex command
      usage: /spacex
      permission: spacex.spacex
      permission-message: You don't have spacex.spacex